export const EMPTY = "";
export const SPACE = " ";
export const DOT = ".";
export const COLON = ":";
export const COMMA = ",";
export const DASH = "-";
export const SEMICOLON = ";";
export const NEWLINE = "\n";
export const TAB = "\t";
export const BACKSPACE = "\b";
export const RETURN = "\r";
export const ZERO = 0;
export const ONE = 1;
export const SECOND = 1000;

export const SHOWING = "Showing";
export const OF = "of";
export const PREVIOUS = "Previous";
export const NEXT = "Next";
